// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	"zhifou/application/follow/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/fans/list",
				Handler: FansListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/follow",
				Handler: FollowHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/follow/list",
				Handler: FollowListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/unfollow",
				Handler: UnFollowHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/follow"),
	)
}
