// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: like.proto

package server

import (
	"context"

	"zhifou/application/like/rpc/internal/logic"
	"zhifou/application/like/rpc/internal/svc"
	"zhifou/application/like/rpc/service"
)

type LikeServer struct {
	svcCtx *svc.ServiceContext
	service.UnimplementedLikeServer
}

func NewLikeServer(svcCtx *svc.ServiceContext) *LikeServer {
	return &LikeServer{
		svcCtx: svcCtx,
	}
}

func (s *LikeServer) Thumbup(ctx context.Context, in *service.ThumbupRequest) (*service.ThumbupResponse, error) {
	l := logic.NewThumbupLogic(ctx, s.svcCtx)
	return l.Thumbup(in)
}

func (s *LikeServer) UnThumbup(ctx context.Context, in *service.UnThumbupRequest) (*service.UnThumbupResponse, error) {
	l := logic.NewUnThumbupLogic(ctx, s.svcCtx)
	return l.UnThumbup(in)
}
