// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: like.proto

package like

import (
	"context"
	"zhifou/application/like/rpc/service"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ThumbupRequest    = service.ThumbupRequest
	ThumbupResponse   = service.ThumbupResponse
	UnThumbupRequest  = service.UnThumbupRequest
	UnThumbupResponse = service.UnThumbupResponse

	Like interface {
		Thumbup(ctx context.Context, in *ThumbupRequest, opts ...grpc.CallOption) (*ThumbupResponse, error)
		UnThumbup(ctx context.Context, in *UnThumbupRequest, opts ...grpc.CallOption) (*UnThumbupResponse, error)
	}

	defaultLike struct {
		cli zrpc.Client
	}
)

func NewLike(cli zrpc.Client) Like {
	return &defaultLike{
		cli: cli,
	}
}

func (m *defaultLike) Thumbup(ctx context.Context, in *ThumbupRequest, opts ...grpc.CallOption) (*ThumbupResponse, error) {
	client := service.NewLikeClient(m.cli.Conn())
	return client.Thumbup(ctx, in, opts...)
}

func (m *defaultLike) UnThumbup(ctx context.Context, in *UnThumbupRequest, opts ...grpc.CallOption) (*UnThumbupResponse, error) {
	client := service.NewLikeClient(m.cli.Conn())
	return client.UnThumbup(ctx, in, opts...)
}
