// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type ThumbupRequest struct {
	BizId  string `json:"biz_id"`  // 业务类型
	ObjId  int64  `json:"obj_id"`  // 点赞对象id
	UserId int64  `json:"user_id"` // 用户id
}

type ThumbupResponse struct {
	BizId string `json:"biz_id"` // 业务类型
	ObjId int64  `json:"obj_id"` // 点赞对象id
}

type UnThumbupRequest struct {
	BizId  string `json:"biz_id"`  // 业务类型
	ObjId  int64  `json:"obj_id"`  // 点赞对象id
	UserId int64  `json:"user_id"` // 用户id
}

type UnThumbupResponse struct {
	BizId string `json:"biz_id"` // 业务类型
	ObjId int64  `json:"obj_id"` // 点赞对象id
}
