// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type FansItem struct {
	UserId     int64 `json:"user_id"`
	FansUserId int64 `json:"fans_user_id"`
	CreateTime int64 `json:"create_time"`
}

type FansListRequest struct {
	UserId   int64 `json:"user_id"`
	Cursor   int64 `json:"cursor"`
	PageSize int64 `json:"page_size"`
}

type FansListResponse struct {
	Items  []*FansItem `json:"items"`
	Cursor int64       `json:"cursor"`
}

type FollowItem struct {
	Id             int64 `json:"id"`
	FollowedUserId int64 `json:"followed_user_id"` // 被关注者
	FansCount      int64 `json:"fans_count"`       // 粉丝数
	CreateTime     int64 `json:"create_time"`      // 关注时间
}

type FollowListRequest struct {
	Id       int64 `json:"id"`
	UserId   int64 `json:"user_id"`
	Cursor   int64 `json:"cursor"`
	PageSize int64 `json:"page_size"`
}

type FollowListResponse struct {
	Items  []*FollowItem `json:"items"`
	Cursor int64         `json:"cursor"`
	IsEnd  bool          `json:"is_end"`
	Id     int64         `json:"id"`
}

type FollowRequest struct {
	UserId         int64 `json:"user_id"`          // 关注者
	FollowedUserId int64 `json:"followed_user_id"` // 被关注者
}

type FollowResponse struct {
}

type UnFollowRequest struct {
	UserId         int64 `json:"user_id"`          // 关注者
	FollowedUserId int64 `json:"followed_user_id"` // 被关注者
}

type UnFollowResponse struct {
}
