// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type CollectItem struct {
	BizId           string `json:"biz_id"`       // 业务类型
	ObjId           int64  `json:"obj_id"`       // 收藏对象id
	CollectTime     string `json:"collect_time"` // 收藏时间
	CollectTimeUnix int64  `json:"collect_time_unix"`
}

type CollectListRequest struct {
	BizId     string `json:"biz_id"` // 业务类型
	UserId    int64  `json:"user_id"`
	Cursor    int64  `json:"cursor"`
	PageSize  int64  `json:"page_size"`
	LastObjId int64  `json:"last_obj_id"`
}

type CollectListResponse struct {
	Items  []*CollectItem `json:"items"`
	BizId  string         `json:"biz_id"` // 业务类型
	Cursor int64          `json:"cursor"`
	IsEnd  bool           `json:"is_end"`
	LastId int64          `json:"last_id"`
}

type CollectRequest struct {
	BizId  string `json:"biz_id"`  // 业务类型
	ObjId  int64  `json:"obj_id"`  // 收藏对象id
	UserId int64  `json:"user_id"` // 用户id
}

type CollectResponse struct {
	BizId string `json:"biz_id"` // 业务类型
	ObjId int64  `json:"obj_id"` // 收藏对象id
}

type UnCollectRequest struct {
	BizId  string `json:"biz_id"`  // 业务类型
	ObjId  int64  `json:"obj_id"`  // 收藏对象id
	UserId int64  `json:"user_id"` // 用户id
}

type UnCollectResponse struct {
	BizId string `json:"biz_id"` // 业务类型
	ObjId int64  `json:"obj_id"` // 收藏对象id
}
