// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: collect.proto

package server

import (
	"context"

	"zhifou/application/collect/rpc/internal/logic"
	"zhifou/application/collect/rpc/internal/svc"
	"zhifou/application/collect/rpc/service"
)

type CollectServer struct {
	svcCtx *svc.ServiceContext
	service.UnimplementedCollectServer
}

func NewCollectServer(svcCtx *svc.ServiceContext) *CollectServer {
	return &CollectServer{
		svcCtx: svcCtx,
	}
}

// 收藏
func (s *CollectServer) Collect(ctx context.Context, in *service.CollectRequest) (*service.CollectResponse, error) {
	l := logic.NewCollectLogic(ctx, s.svcCtx)
	return l.Collect(in)
}

// 取消收藏
func (s *CollectServer) UnCollect(ctx context.Context, in *service.UnCollectRequest) (*service.UnCollectResponse, error) {
	l := logic.NewUnCollectLogic(ctx, s.svcCtx)
	return l.UnCollect(in)
}

// 收藏列表
func (s *CollectServer) CollectList(ctx context.Context, in *service.CollectListRequest) (*service.CollectListResponse, error) {
	l := logic.NewCollectListLogic(ctx, s.svcCtx)
	return l.CollectList(in)
}
