// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type ArticleDeleteRequest struct {
	UserId    int64 `json:"user_id"`    // 用户ID
	ArticleId int64 `json:"article_id"` // 文章ID
}

type ArticleDeleteResponse struct {
}

type ArticleDetailRequest struct {
	ArticleId int64 `json:"article_id"` // 文章ID
}

type ArticleDetailResponse struct {
	Article *ArticleItem `json:"article"` // 文章详情
}

type ArticleItem struct {
	Id              int64  `json:"id"`                // 文章ID
	Title           string `json:"title"`             // 文章标题
	Content         string `json:"content"`           // 文章内容
	Description     string `json:"description"`       // 文章描述
	Cover           string `json:"cover"`             // 封面图片
	CommentCount    int64  `json:"comment_count"`     // 评论数
	LikeCount       int64  `json:"like_count"`        // 点赞数
	CollectCount    int64  `json:"collect_count"`     // 收藏数
	PublishTimeUnix int64  `json:"publish_time_unix"` // 发布时间 (Unix 时间戳)
	PublishTime     string `json:"publish_time"`      // 发布时间 (字符串格式)
	AuthorId        int64  `json:"author_id"`         // 作者ID
}

type ArticlesRequest struct {
	UserId    int64 `json:"user_id"`    // 用户ID
	Cursor    int64 `json:"cursor"`     // 游标
	PageSize  int64 `json:"page_size"`  // 每页大小
	SortType  int32 `json:"sort_type"`  // 排序类型
	ArticleId int64 `json:"article_id"` // 文章ID
}

type ArticlesResponse struct {
	Items         []*ArticleItem `json:"items"`           // 文章列表
	IsEnd         bool           `json:"is_end"`          // 是否结束
	Cursor        int64          `json:"cursor"`          // 游标
	LastArticleId int64          `json:"last_article_id"` // 上一篇文章ID
}

type PublishRequest struct {
	UserId      int64  `json:"user_id"`     // 用户ID
	Title       string `json:"title"`       // 文章标题
	Content     string `json:"content"`     // 文章内容
	Description string `json:"description"` // 文章描述
	Cover       string `json:"cover"`       // 封面图片
}

type PublishResponse struct {
	ArticleId int64 `json:"article_id"` // 文章ID
}

type SearchArticleRequest struct {
	Query     string `json:"query"`      // 搜索关键词
	PageNum   int64  `json:"page_num"`   // 页码
	PageSize  int64  `json:"page_size"`  // 每页大小
	Cursor    int64  `json:"cursor"`     // 游标
	SortType  int32  `json:"sort_type"`  // 排序类型
	ArticleId int64  `json:"article_id"` // 文章ID
}

type SearchArticleResponse struct {
	Articles      []*ArticleItem `json:"articles"`        // 文章列表
	IsEnd         bool           `json:"is_end"`          // 是否结束
	PageNum       int64          `json:"page_num"`        // 当前页码
	LastArticleId int64          `json:"last_article_id"` // 上一篇文章ID
	Cursor        int64          `json:"cursor"`          // 游标
}

type UploadCoverResponse struct {
	CoverUrl string `json:"cover_url"`
}
